In [5]:
import random
N=4
M=5
[[random.random() for i in range(M)] for j in range(N)]

[[0.07983684114267997,
  0.5797442213554005,
  0.015236003918717378,
  0.9583211503037363,
  0.7790711137555314],
 [0.5648365122969123,
  0.6949784882161509,
  0.6202108942269896,
  0.7620983176190145,
  0.4943110163745058],
 [0.06525060319797027,
  0.2568816340268669,
  0.9507226013330996,
  0.9556206019248594,
  0.174458838351781],
 [0.9616311706284202,
  0.5403831735595771,
  0.5536881982534358,
  0.9673187557639352,
  0.02768812895743944]]

In [6]:
import numpy as np
import random
array = np.random.randint(1,1000,size=(4,5))
print(array)

[[633 430 366 607 343]
 [943 830 867 925 176]
 [819 849 619 306 361]
 [890 274 929 846 273]]
