In [2]:
import numpy as np
import random
array = np.random.randint(1,1000,size=(4,9))
print(array)
s_a = np.hsplit(array,3)
print(s_a)

[[590 861 365 726 683 962 923 568 426]
 [317 595 208 717 640 299  24 782 368]
 [603 217 811 748 569   7 578 707 946]
 [  9 957 603 314 686 778 191 199 811]]
[array([[590, 861, 365],
       [317, 595, 208],
       [603, 217, 811],
       [  9, 957, 603]]), array([[726, 683, 962],
       [717, 640, 299],
       [748, 569,   7],
       [314, 686, 778]]), array([[923, 568, 426],
       [ 24, 782, 368],
       [578, 707, 946],
       [191, 199, 811]])] 